apiVersion: v1
kind: ConfigMap
metadata:
  name: wf-aks-sample-deploy-config
  namespace: sample-app-namespace-1787113322033
  labels:
    app.kubernetes.io/name: wf-aks-sample-deploy
    kubernetes.azure.com/generator: devhub
data: