apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wf-aks-sample-deploy
  labels:
    app.kubernetes.io/name: wf-aks-sample-deploy
    app.kubernetes.io/part-of: wf-aks-sample-deploy-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: wf-aks-sample-deploy